FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY nazrinserver_c.c .

RUN gcc nazrinserver_c.c -o nazrinserver_c -lmysqlclient

EXPOSE 5004
CMD ["./nazrinserver_c"]



