FROM python:3.10-slim

WORKDIR /app

COPY m_server.py .
# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
 && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir mysql-connector-python

EXPOSE 5005



CMD ["python", "m_server.py"]
