FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY fathu_c_server.c .

RUN gcc fathu_c_server.c -o fathu_server_c -lmysqlclient

EXPOSE 5005
CMD ["./fathu_server_c"]
